const layout =
[
  { "key": "`", "code": "Backquote", "shift": "~"},
  { "key": "1", "code": "Digit1", "shift": "!"},
  { "key": "2", "code": "Digit2", "shift": "@"},
  { "key": "3", "code": "Digit3", "shift": "#"},
  { "key": "4", "code": "Digit4", "shift": "$"},
  { "key": "5", "code": "Digit5", "shift": "%"},
  { "key": "6", "code": "Digit6", "shift": "^"},
  { "key": "7", "code": "Digit7", "shift": "&"},
  { "key": "8", "code": "Digit8", "shift": "*"},
  { "key": "9", "code": "Digit9", "shift": "("},
  { "key": "0", "code": "Digit0", "shift": ")"},
  { "key": "-", "code": "Minus", "shift": "_"},
  { "key": "=", "code": "Equal", "shift": "+"},
  { "key": "Backspace", "code": "Backspace", "shift": null, "end": true, "extras": ["keyboard__button_wide-3","functional"]},
  { "key": "Tab", "code": "Tab", "shift": null,"extras": ["keyboard__button_wide-0","functional"]},
  { "key": "q", "code": "KeyQ", "shift": "Q"},
  { "key": "w", "code": "KeyW", "shift": "W"},
  { "key": "e", "code": "KeyE", "shift": "E"},
  { "key": "r", "code": "KeyR", "shift": "R"},
  { "key": "t", "code": "KeyT", "shift": "T"},
  { "key": "y", "code": "KeyY", "shift": "Y"},
  { "key": "u", "code": "KeyU", "shift": "U"},
  { "key": "i", "code": "KeyI", "shift": "I"},
  { "key": "o", "code": "KeyO", "shift": "O"},
  { "key": "p", "code": "KeyP", "shift": "P"},
  { "key": "[", "code": "BracketLeft", "shift": "{"},
  { "key": "]", "code": "BracketRight", "shift": "}"},
  { "key": "\\", "code": "Backslash", "shift": "|"},
  { "key": "Delete", "code": "Delete", "shift": null, "end": true,"extras":["functional"] },
  { "key": "CapsLock", "code": "CapsLock", "shift": null,"extras": ["keyboard__button_wide-2","functional"]},
  { "key": "a", "code": "KeyA", "shift": "A"},
  { "key": "s", "code": "KeyS", "shift": "S"},
  { "key": "d", "code": "KeyD", "shift": "D"},
  { "key": "f", "code": "KeyF", "shift": "F"},
  { "key": "g", "code": "KeyG", "shift": "G"},
  { "key": "h", "code": "KeyH", "shift": "H"},
  { "key": "j", "code": "KeyJ", "shift": "J"},
  { "key": "k", "code": "KeyK", "shift": "K"},
  { "key": "l", "code": "KeyL", "shift": "L"},
  { "key": ";", "code": "Semicolon", "shift":":" },
  { "key": "'", "code": "Quote", "shift": "\""},
  { "key": "Enter", "code": "Enter", "shift": null, "end": true,"extras": ["keyboard__button_wide-2","functional"] },
  { "key": "Shift", "code": "ShiftLeft", "shift": null,"extras": ["keyboard__button_wide-2","functional"]},
  { "key": "z", "code": "KeyZ", "shift": "Z"},
  { "key": "x", "code": "KeyX", "shift": "X"},
  { "key": "c", "code": "KeyC", "shift": "C"},
  { "key": "v", "code": "KeyV", "shift": "V"},
  { "key": "b", "code": "KeyB", "shift": "B"},
  { "key": "n", "code": "KeyN", "shift": "N"},
  { "key": "m", "code": "KeyM", "shift": "M"},
  { "key": ",", "code": "Comma", "shift": "<"},
  { "key": ".", "code": "Period", "shift": ">"},
  { "key": "/", "code": "Slash", "shift": "?"},
  { "key": "ArrowUp", "code": "ArrowUp", "shift": null,"extras":["functional"]},
  { "key": "Shift", "code": "ShiftRight", "shift": null,"extras": ["keyboard__button_wide-2","functional"], "end": true },
  
  { "key": "Control", "code": "ControlLeft", "shift": null,"extras": ["keyboard__button_wide-0","functional"]},
  { "key": "Win", "code": "MetaLeft", "shift": null,"extras":["functional"]},
  { "key": "Alt", "code": "AltLeft", "shift": null,"extras":["functional"]},
  { "key": " ", "code": "Space", "shift": null,"extras": ["keyboard__button_space"]},
  { "key": "Alt", "code": "AltRight", "shift": null,"extras":["functional"]},
  { "key": "Control", "code": "ControlRight", "shift": null,"extras": ["keyboard__button_wide-0","functional"]},
  { "key": "ArrowLeft", "code": "ArrowLeft", "shift": null,"extras":["functional"]},
  { "key": "ArrowDown", "code": "ArrowDown", "shift": null,"extras":["functional"]},
  { "key": "ArrowRight", "code": "ArrowRight", "shift": null,"extras":["functional"]}
]
export default layout