const layout = 
[
    { "key": "`", "code": "Backquote", "shift": "~"},
    { "key": "1", "code": "Digit1", "shift": "!"},
    { "key": "2", "code": "Digit2", "shift": "\""},
    { "key": "3", "code": "Digit3", "shift": "№"},
    { "key": "4", "code": "Digit4", "shift": ";"},
    { "key": "5", "code": "Digit5", "shift": "%"},
    { "key": "6", "code": "Digit6", "shift": ":"},
    { "key": "7", "code": "Digit7", "shift": "?"},
    { "key": "8", "code": "Digit8", "shift": "*"},
    { "key": "9", "code": "Digit9", "shift": "("},
    { "key": "0", "code": "Digit0", "shift": ")"},
    { "key": "-", "code": "Minus", "shift": "_"},
    { "key": "=", "code": "Equal", "shift": "+"},
    { "key": "Backspace", "code": "Backspace", "shift": null, "end": true, "extras": ["keyboard__button_wide-3","functional"]},
    { "key": "Tab", "code": "Tab", "shift": null,"extras": ["keyboard__button_wide-0","functional"]},
    { "key": "й", "code": "KeyQ", "shift": "Й"},
    { "key": "ц", "code": "KeyW", "shift": "Ц"},
    { "key": "у", "code": "KeyE", "shift": "У"},
    { "key": "к", "code": "KeyR", "shift": "К"},
    { "key": "е", "code": "KeyT", "shift": "Е"},
    { "key": "н", "code": "KeyY", "shift": "Н"},
    { "key": "г", "code": "KeyU", "shift": "Г"},
    { "key": "ш", "code": "KeyI", "shift": "Ш"},
    { "key": "щ", "code": "KeyO", "shift": "Щ"},
    { "key": "з", "code": "KeyP", "shift": "З"},
    { "key": "х", "code": "BracketLeft", "shift": "Х"},
    { "key": "ъ", "code": "BracketRight", "shift": "Ъ"},
    { "key": "\\", "code": "Backslash", "shift": "/"},
    { "key": "Delete", "code": "Delete", "shift": null, "end": true,"extras":["functional"] },
    { "key": "CapsLock", "code": "CapsLock", "shift": null,"extras": ["keyboard__button_wide-2","functional"]},
    { "key": "ф", "code": "KeyA", "shift": "Ф"},
    { "key": "ы", "code": "KeyS", "shift": "Ы"},
    { "key": "в", "code": "KeyD", "shift": "В"},
    { "key": "а", "code": "KeyF", "shift": "А"},
    { "key": "п", "code": "KeyG", "shift": "П"},
    { "key": "р", "code": "KeyH", "shift": "Р"},
    { "key": "о", "code": "KeyJ", "shift": "О"},
    { "key": "л", "code": "KeyK", "shift": "Л"},
    { "key": "д", "code": "KeyL", "shift": "Д"},
    { "key": "ж", "code": "Semicolon", "shift":"Ж" },
    { "key": "э", "code": "Quote", "shift": "Э"},
    { "key": "Enter", "code": "Enter", "shift": null, "end": true,"extras": ["keyboard__button_wide-2","functional"] },
    { "key": "Shift", "code": "ShiftLeft", "shift": null,"extras": ["keyboard__button_wide-2","functional"]},
    { "key": "я", "code": "KeyZ", "shift": "Я"},
    { "key": "ч", "code": "KeyX", "shift": "Ч"},
    { "key": "с", "code": "KeyC", "shift": "С"},
    { "key": "м", "code": "KeyV", "shift": "М"},
    { "key": "и", "code": "KeyB", "shift": "И"},
    { "key": "т", "code": "KeyN", "shift": "Т"},
    { "key": "ь", "code": "KeyM", "shift": "Ь"},
    { "key": "б", "code": "Comma", "shift": "Б"},
    { "key": "ю", "code": "Period", "shift": "Ю"},
    { "key": ".", "code": "Slash", "shift": ","},
    { "key": "ArrowUp", "code": "ArrowUp", "shift": null,"extras":["functional"]},
    { "key": "Shift", "code": "ShiftRight", "shift": null, "extras": ["keyboard__button_wide-2","functional"], "end": true },

    { "key": "Control", "code": "ControlLeft", "shift": null,"extras": ["keyboard__button_wide-0","functional"]},
    { "key": "Win", "code": "MetaLeft", "shift": null,"extras":["functional"]},
    { "key": "Alt", "code": "AltLeft", "shift": null,"extras":["functional"]},
    { "key": " ", "code": "Space", "shift": null,"extras": ["keyboard__button_space"]},
    { "key": "Alt", "code": "AltRight", "shift": null,"extras":["functional"]},
    { "key": "Control", "code": "ControlRight", "shift": null,"extras": ["keyboard__button_wide-0","functional"]},
    { "key": "ArrowLeft", "code": "ArrowLeft", "shift": null,"extras":["functional"]},
    { "key": "ArrowDown", "code": "ArrowDown", "shift": null,"extras":["functional"]},
    { "key": "ArrowRight", "code": "ArrowRight", "shift": null,"extras":["functional"]}
  ]
export default layout;